### PR TITLE
Added create and update post API endpoints

### PR DESCRIPTION
**Pull request by stygian-96**
# Pull Request 

## Proposed Changes
- Resolved issue #23 
- Added create and update post API endpoints
- Added code for uploading image to mongo gridfs using multer
- Refactored Code

## Types of changes made
- [ ] Fixed Bug
- [x] Added new Features
- [x] Edited Documentations
- [ ] Enhanced the working of code
- [ ] Additional Changes

## Checklist:
- [x] My code follows the Mentioned Guidelines for the project
- [x] I have self-reviewed the changes made
- [x] I have made the changes easy to understand by adding comments
- [x] My changes does not generate new warnings/errors
- [x] I have attached relevant screenshots to display the changes made
- [x] I have made the required changes to the documentations

### CODE REVIEW

**Comment by stygian-96** [comment]
@sarthakm21 pls review

**Comment by sarthakm21** [comment]
@Elemento24 the paginate function you have used is causing some errors. Review it please once the PR is merged. Rest of the routes are working fine......

**Comment by sarthakm21** [comment]
Looks good to me!

**Comment by stygian-96** [comment]
Nice

**Pull request merged**
