### PR TITLE
Added function to update user's email

### PR DESCRIPTION
**Pull request by uglyprincess**
# Pull Request 

## Proposed Changes
- Added a function that will update the User's email from the sign up page itself.

## Types of changes made
- [ ] Fixed Bug
- [x] Added new Features
- [x] Edited Documentations
- [x] Enhanced the working of code
- [ ] Additional Changes

## Additional Info
-

## Viability of Code
- I tested the code on my local server by tracking the live changes using Robo 3T

#### Mention(*if any*) specific Test Configurations used:
-

## Screenshots or GIFs (*if any*)
Attach screenshots of the changes made for easy reference.
Original | Updated
:-----:|:-----:
*Attach_Original_Screenshot* | *Attach_Updated_Screenshot*

## Checklist:
- [x] My code follows the Mentioned Guidelines for the project
- [x] I have self-reviewed the changes made
- [x] I have made the changes easy to understand by adding comments
- [x] My changes does not generate new warnings/errors
- [ ] I have attached relevant screenshots to display the changes made
- [x] I have made the required changes to the documentations

### CODE REVIEW

**Comment by uglyprincess** [comment]
@2802harsh @Tlazypanda please review these changes :))

**Comment by 2802harsh** [comment]
Ig we can save the email received from req.body in email field instead of googleId
googleId will store the unique ID when user logs in thru google

**Review by 2802harsh — CHANGES_REQUESTED** [review]
Change googleId to email
Also if that field does not alreday exist in usermodel then include it
googleId field is already being used - it's only for users who login thru google (to save their unique Google id)

**Comment by uglyprincess** [comment]
> Change googleId to email
> Also if that field dies not alreday exist in usermodel then include it
> googleId field is already being used - it's only for users who login thru google (to save their unique Google id)

Okay, will do!

**Comment by uglyprincess** [comment]
@2802harsh done the requested changes + resolved merge conflicts.

**Review by 2802harsh — APPROVED** [review]

**Pull request merged**
